
team_map = {'ATL': 'Atlanta Falcons',
 'DAL': 'Dallas Cowboys',
 'PIT': 'Pittsburgh Steelers',
 'CIN': 'Cincinnati Bengals',
 'WAS': 'Washington Football Team',
 'SEA': 'Seattle Seahawks',
 'CHI': 'Chicago Bears',
 'TEN': 'Tennessee Titans',
 'SFO': 'San Francisco 49ers',
 'TAM': 'Tampa Bay Buccaneers',
 'HOU': 'Houston Texans',
 'JAX': 'Jacksonville Jaguars',
 'BUF': 'Buffalo Bills',
 'KAN': 'Kansas City Chiefs',
 'NYJ': 'New York Jets',
 'LAR': 'Los Angeles Rams',
 'BAL': 'Baltimore Ravens',
 'CAR': 'Carolina Panthers',
 'LAC': 'Los Angeles Chargers',
 'NYG': 'New York Giants',
 'OAK': 'Oakland Raiders',
 'MIN': 'Minnesota Vikings',
 'NWE': 'New England Patriots',
 'CLE': 'Cleveland Browns',
 'MIA': 'Miami Dolphins',
 'ARI': 'Arizona Cardinals',
 'DET': 'Detroit Lions',
 'PHI': 'Philadelphia Eagles',
 'IND': 'Indianapolis Colts',
 'NOR': 'New Orleans Saints',
 'DEN': 'Denver Broncos',
 'GNB': 'Green Bay Packers',
 'LVR': 'Las Vegas Raiders'}

team_map_inv = {'Atlanta Falcons': 'ATL',
 'Dallas Cowboys': 'DAL',
 'Pittsburgh Steelers': 'PIT',
 'Cincinnati Bengals': 'CIN',
 'Washington Redskins': 'WAS',
 'Seattle Seahawks': 'SEA',
 'Chicago Bears': 'CHI',
 'Tennessee Titans': 'TEN',
 'San Francisco 49ers': 'SFO',
 'Tampa Bay Buccaneers': 'TAM',
 'Houston Texans': 'HOU',
 'Jacksonville Jaguars': 'JAX',
 'Buffalo Bills': 'BUF',
 'Kansas City Chiefs': 'KAN',
 'New York Jets': 'NYJ',
 'Los Angeles Rams': 'LAR',
 'Baltimore Ravens': 'BAL',
 'Carolina Panthers': 'CAR',
 'Los Angeles Chargers': 'LAC',
 'New York Giants': 'NYG',
 'Oakland Raiders': 'OAK',
 'Minnesota Vikings': 'MIN',
 'New England Patriots': 'NWE',
 'Cleveland Browns': 'CLE',
 'Miami Dolphins': 'MIA',
 'Arizona Cardinals': 'ARI',
 'Detroit Lions': 'DET',
 'Philadelphia Eagles': 'PHI',
 'Indianapolis Colts': 'IND',
 'New Orleans Saints': 'NOR',
 'Denver Broncos': 'DEN',
 'Green Bay Packers': 'GNB',
 'Las Vegas Raiders': 'LVR',
 'Washington Football Team': 'WAS'}

team_map_2 = {'Falcons': 'ATL',
 'Cowboys': 'DAL',
 'Steelers': 'PIT',
 'Bengals': 'CIN',
 'WASFootballTeam': 'WAS',
 'Seahawks': 'SEA',
 'Bears': 'CHI',
 'Titans': 'TEN',
 '49ers': 'SFO',
 'Buccaneers': 'TAM',
 'Texans': 'HOU',
 'Jaguars': 'JAX',
 'Bills': 'BUF',
 'Chiefs': 'KAN',
 'Jets': 'NYJ',
 'Rams': 'LAR',
 'Ravens': 'BAL',
 'Panthers': 'CAR',
 'Chargers': 'LAC',
 'Giants': 'NYG',
 'Raiders': 'OAK',
 'Vikings': 'MIN',
 'Patriots': 'NWE',
 'Browns': 'CLE',
 'Dolphins': 'MIA',
 'Cardinals': 'ARI',
 'Lions': 'DET',
 'Eagles': 'PHI',
 'Colts': 'IND',
 'Saints': 'NOR',
 'Broncos': 'DEN',
 'Packers': 'GNB',
 'Raiders': 'LVR'}
